### ISSUE TITLE
PostTaxonomy::register function allows spaced name to be passed into register_taxonomy

### ISSUE THREAD

**Issue by Xachman** [dwalkr/wp-admin-utility#2]
When a spaced name is passed into register_taxonomy the function allows it but then all the javascript breaks that allow adding taxonomies in the admin.  This can be avoided by using labels and changing the name to a none spaced value however since we use the name to generate labels if labels are not included it may be a good idea to string to lower and replace the spaces with underscores in the name value.

**Comment by dwalkr** [comment]
The taxonomy name is passed directly into WordPress taxonomy API as if you had declared the taxonomy normally.

This behavior mirrors vanilla WordPress behavior and should therefore not be altered.
