### ISSUE TITLE
checkbox save problem

### ISSUE THREAD

**Issue by dwalkr** [dwalkr/wp-admin-utility#9]
checkboxes may not unset data correctly when not checked and item is saved

**Comment by Xachman** [comment]
Maybe a solution to this problem is to check if any of the custom fields are set in the post then allow the whole transaction to continue.

Of course if your whole cpt is checkboxes this solution will not work.

**Comment by dwalkr** [comment]
f8b39fe94b71f00e3a81f340d491eea7f51dfb1f is necessary because otherwise it destroys data when doing quick edit, right?

Last time I looked into this there was no canonical way to determine if a user was doing a quick edit vs a full edit, hence the problem.

It just occurred to me, though, that we could add a hidden field named e.g. "DOING_QUICKEDIT" and check for that when updating

It's not an ideal fix as checkboxes would still be non-nullable when used in quick edit, but considering you can't assign fields to quickedit via admin utility, this isn't really a problem for now. If we add that feature in the future we will need to remember this, and ultimately update the code to null fields when they're used in quickedit.

Or we could just always render checkboxes as select / use some stupid css hack with probably radio buttons or something

**Comment by dwalkr** [comment]
The method for adding custom quickedit items is crazy, I now remember why I never bothered in the first place

I've decided to go ahead with quickedit detection and destructive saves. I don't expect admin utility to ever handle quickedit fields, quickedit is stupid
